const express = require('express')
const app = express()
// const cors = require('cors')
// const api = require('./api')
var login = require('./login/login')
var info = require('./info/info')
var enumeration = require('./enum/enum')
// app.all('*', function(req, res, next) {
//   res.header('Access-Control-Allow-Origin', '*')
//   res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept')
//   res.header('Access-Control-Allow-Methods', 'PUT,POST,GET,DELETE,OPTIONS')
//   res.header('X-Powered-By', ' 3.2.1')
//   res.header('Content-Type', 'application/json;charset=utf-8')
//   next()
// })
// 引入处理post数据的模块
const bodyParser = require('body-parser')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: false }))
// app.use(cors)
// 登录页
// app.use('/login', api)
// app.use('/api', birds)
app.use(login)
app.use(info)
app.use(enumeration)
// app.use(api)
// console.log(api)
// console.log(birds)
// api(app)

app.listen(8088)
console.log('success listen…………')
